version: '3.3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superSqlPassw0rD
      MYSQL_DATABASE: agence_immo
      MYSQL_USER: immo_user
      MYSQL_PASSWORD: simpleSqlPass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d
    container_name: ho-sqlserver
  webserver:
    build: web_server/
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    container_name: ho-webserver